site_name: Yaya Sy
theme:
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark
  features:
    # - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.sections # sections are rendered as groups in the sidebar
    - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    - toc.integrate # show table of contents to navigation panel
    - header.autohide

    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button

    - content.code.annotate

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/yaya-sy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/seygalare
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/yaya-sy-a8473023a/